### PR TITLE
ALgo

### PR DESCRIPTION
**Pull request by Baeron18**
added a random pivoting quick sort solution with time function in c

### CODE REVIEW

**Comment by Baeron18** [comment]
done

**Comment by Baeron18** [comment]
I need to add only the question.md right

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by chandrikadeb7** [comment]
> I need to add only the question.md right Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10 From: Chandrika Deb<mailto:notifications@github.com> Sent: 05 October 2020 20:04 To: chandrikadeb7/Hacktoberfest_2020<mailto:Hacktoberfest_2020@noreply.github.com> Cc: NEEL GHOSH<mailto:neelanjan22@hotmail.com>; Mention<mailto:mention@noreply.github.com> Subject: Re: [chandrikadeb7/Hacktoberfest_2020] Cp (#58)

Task 3 folder is for algorithms while Task 1 has CP questions only.

**Comment by Baeron18** [comment]
Ohkay thanks


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Review by Baeron18 — COMMENTED** [review]
added to Task3.PLs review

**Comment by chandrikadeb7** [comment]
Please make a new PR with both programs in Task 3 folder and delete question.md files

**Comment by Baeron18** [comment]
only the programs or will I put them in a directory

**Pull request closed without merging**
