### PR TITLE
 compressionalgorithm.kt

### PR DESCRIPTION
**Pull request by drraghavendra**
folder structure created for Compression Algorithm

### CODE REVIEW

**Comment by drraghavendra** [comment]
[Uploading Compression.zip…]()

**Comment by drraghavendra** [comment]
[Compression.zip](https://github.com/chandrikadeb7/Hacktoberfest_2020/files/5321047/Compression.zip)

**Comment by chandrikadeb7** [comment]
@drraghavendra Code incomplete.

**Comment by drraghavendra** [comment]
Pull Request 54  explained in detail which is same as that of PR 29.Hence Closing the incomplete PR

**Pull request closed without merging**
