### PR TITLE
Added Implementation of Priority Queue Using Array

### PR DESCRIPTION
**Pull request by archanakumari-ak**

### CODE REVIEW

**Review by nimishbongale — COMMENTED** [review]
Great work @archanakumari-ak!

We are nearly done. As a last review, can we have a small explanation & sample input/output cases on the top of the program as a part of a multiline comment?

**Comment by archanakumari-ak** [comment]
Sure! I am working on this and will add it soon.

**Comment by archanakumari-ak** [comment]
Kindly review and approve.

**Review by nimishbongale — APPROVED** [review]
Great work @archanakumari-ak! 🚀 

You are now ready to contribute to cool open source projects! 😄

**Pull request merged**
